
import { Category, Question, Difficulty } from './types';

const DISNEY_POOL: Partial<Question>[] = [
  { text: "What is the name of the prince in 'The Little Mermaid'?", options: ["Prince Eric", "Prince Phillip", "Prince Naveen", "Prince Florian"], correctIndex: 0, explanation: "Prince Eric is the love interest of Ariel." },
  { text: "Which Disney film features a song called 'Cruella de Vil'?", options: ["The Aristocats", "101 Dalmatians", "Lady and the Tramp", "Oliver & Company"], correctIndex: 1, explanation: "The song was written by Roger Radcliffe in the movie." },
  { text: "What are the names of Hades' two sidekicks in Hercules?", options: ["Pain and Panic", "Fear and Dread", "Lock and Shock", "Flotsam and Jetsam"], correctIndex: 0, explanation: "Pain and Panic are the shape-shifting minions of Hades." },
  { text: "Which was the first full-length animated movie released by Disney?", options: ["Pinocchio", "Bambi", "Snow White", "Fantasia"], correctIndex: 2, explanation: "Snow White and the Seven Dwarfs premiered in 1937." },
  { text: "In 'Finding Nemo', what is the address Dory remembers?", options: ["42 Wallaby Way", "123 Sydney St", "10 Downing Street", "21 Jump Street"], correctIndex: 0, explanation: "P. Sherman, 42 Wallaby Way, Sydney." },
  { text: "What is the name of the spirit of adventure ship in 'Up'?", options: ["The Spirit of Adventure", "The Hindenburg", "The Goodyear", "The Discovery"], correctIndex: 0, explanation: "Charles Muntz's airship is named The Spirit of Adventure." },
  { text: "How many brothers does Prince Hans have in 'Frozen'?", options: ["8", "10", "12", "15"], correctIndex: 2, explanation: "Hans is the youngest of 13 brothers (so he has 12 brothers)." },
  { text: "What is the name of the island Moana lives on?", options: ["Te Fiti", "Motunui", "Oahu", "Maui"], correctIndex: 1, explanation: "Moana is the daughter of the chief of Motunui." },
  { text: "What kind of animal is Flower in the movie 'Bambi'?", options: ["Rabbit", "Deer", "Skunk", "Squirrel"], correctIndex: 2, explanation: "Flower is a very shy skunk." },
  { text: "What does the 'Epcot' in Epcot Center stand for?", options: ["Experimental Prototype Community of Tomorrow", "Every Person Comes Out Tired", "Electric Power Community of Technology", "Extended Park Community of Tomorrow"], correctIndex: 0, explanation: "Walt Disney's original vision was a planned community." },
  { text: "Who was the first Disney princess to have a child?", options: ["Cinderella", "Belle", "Ariel", "Mulan"], correctIndex: 2, explanation: "Ariel's daughter, Melody, appears in the sequel 'Return to the Sea'." },
  { text: "In 'Toy Story', who is the voice of Woody?", options: ["Tim Allen", "Tom Hanks", "Bill Murray", "Jim Carrey"], correctIndex: 1, explanation: "Tom Hanks has voiced Woody in every major film." },
  { text: "Which movie is 'Circle of Life' from?", options: ["Tarzan", "Aladdin", "The Lion King", "Brother Bear"], correctIndex: 2, explanation: "It was written by Elton John and Tim Rice." },
  { text: "What is the name of the clock in 'Beauty and the Beast'?", options: ["Lumiere", "Cogsworth", "Mrs. Potts", "Maurice"], correctIndex: 1, explanation: "Cogsworth is the butler turned clock." },
  { text: "Which Disney character says: 'Fish are friends, not food'?", options: ["Nemo", "Dory", "Bruce", "Marlin"], correctIndex: 2, explanation: "Bruce the great white shark leads the support group." },
  { text: "What is the name of Maleficent's pet raven?", options: ["Diablo", "Malum", "Corvus", "Shadow"], correctIndex: 0, explanation: "In the 1959 film, the raven is named Diablo." },
  { text: "What is the name of the town where 'Cars' takes place?", options: ["Radiator Springs", "Route 66", "Wheelville", "Piston City"], correctIndex: 0, explanation: "It's located along historic Route 66." },
  { text: "What color are Mickey Mouse's shorts?", options: ["Blue", "Red", "Yellow", "Green"], correctIndex: 1, explanation: "Mickey is famous for his red shorts with white buttons." },
  { text: "Who is the fashion designer in 'The Incredibles'?", options: ["Vogue", "Edna Mode", "Coco Chanel", "Mirage"], correctIndex: 1, explanation: "Edna Mode, 'No Capes!'" },
  { text: "What is the name of the dragon in 'Mulan'?", options: ["Mushu", "Sisu", "Falkor", "Drogon"], correctIndex: 0, explanation: "Mushu is Mulan's guardian, voiced by Eddie Murphy." },
  { text: "What is the name of the dog in 'Up'?", options: ["Dug", "Bolt", "Copper", "Buster"], correctIndex: 0, explanation: "Dug is the golden retriever who can talk via a collar." },
  { text: "What is the name of the kingdom in 'Tangled'?", options: ["Corona", "Arendelle", "DunBroch", "Agrabah"], correctIndex: 0, explanation: "Rapunzel is the lost princess of Corona." },
  { text: "Who is the main villain in 'The Lion King'?", options: ["Scar", "Zira", "Jafar", "Gaston"], correctIndex: 0, explanation: "Scar is Mufasa's brother and Simba's uncle." },
  { text: "What is the name of the cat in 'Alice in Wonderland'?", options: ["Cheshire Cat", "Lucifer", "Figaro", "Dinah"], correctIndex: 0, explanation: "The Cheshire Cat is known for its mischievous grin." },
  { text: "In 'Ratatouille', what is the name of the rat?", options: ["Remy", "Emile", "Django", "Gusteau"], correctIndex: 0, explanation: "Remy dreams of becoming a great French chef." }
];

const MUSIC_POOL: Partial<Question>[] = [
  { text: "Which band performed the hit 'Bohemian Rhapsody'?", options: ["The Beatles", "Queen", "Led Zeppelin", "Pink Floyd"], correctIndex: 1, explanation: "Released in 1975, it's one of the best-selling singles of all time." },
  { text: "Who is known as the 'King of Pop'?", options: ["Elvis Presley", "Michael Jackson", "Prince", "Justin Timberlake"], correctIndex: 1, explanation: "Michael Jackson earned the title through his record-breaking career." },
  { text: "What was the name of the Spice Girls' debut single?", options: ["Say You'll Be There", "2 Become 1", "Wannabe", "Spice Up Your Life"], correctIndex: 2, explanation: "Released in 1996, 'Wannabe' made them global stars." },
  { text: "Which singer released the album '21'?", options: ["Adele", "Taylor Swift", "Beyoncé", "Rihanna"], correctIndex: 0, explanation: "Adele's '21' includes 'Rolling in the Deep' and 'Someone Like You'." },
  { text: "Which iconic festival took place in 1969?", options: ["Glastonbury", "Woodstock", "Coachella", "Lollapalooza"], correctIndex: 1, explanation: "Woodstock is the defining moment of the 60s counterculture." },
  { text: "Who sang the 1980s hit 'Girls Just Want to Have Fun'?", options: ["Madonna", "Cyndi Lauper", "Whitney Houston", "Tina Turner"], correctIndex: 1, explanation: "Cyndi Lauper released this feminist anthem in 1983." },
  { text: "What is the name of Beyoncé's fan base?", options: ["The Beliebers", "The Barbz", "The Beyhive", "The Swifties"], correctIndex: 2, explanation: "The Beyhive is one of the most dedicated fan communities." },
  { text: "Which band's members are John, Paul, George, and Ringo?", options: ["The Rolling Stones", "The Who", "The Beatles", "The Beach Boys"], correctIndex: 2, explanation: "The Fab Four changed music forever." },
  { text: "Which artist holds the record for the most Grammy wins?", options: ["Beyoncé", "Georg Solti", "Quincy Jones", "Stevie Wonder"], correctIndex: 0, explanation: "Beyoncé broke the record in 2023, now holding 32 Grammys." },
  { text: "Who sang 'Purple Rain'?", options: ["David Bowie", "Prince", "Rick James", "George Michael"], correctIndex: 1, explanation: "Prince released the album and film of the same name in 1984." },
  { text: "Which year did ABBA win the Eurovision Song Contest?", options: ["1970", "1972", "1974", "1976"], correctIndex: 2, explanation: "They won with 'Waterloo', starting their global career." },
  { text: "What is the best-selling album of all time worldwide?", options: ["Back in Black", "The Dark Side of the Moon", "Thriller", "The Bodyguard"], correctIndex: 2, explanation: "Michael Jackson's Thriller has sold over 70 million copies." },
  { text: "Who is the lead singer of U2?", options: ["The Edge", "Bono", "Sting", "Phil Collins"], correctIndex: 1, explanation: "Bono has been the front man since the band started in Dublin." },
  { text: "Which pop star is known as 'The Material Girl'?", options: ["Britney Spears", "Madonna", "Lady Gaga", "Katy Perry"], correctIndex: 1, explanation: "Madonna released the song 'Material Girl' in 1984." },
  { text: "Which country did the band AC/DC originate from?", options: ["USA", "UK", "Australia", "Canada"], correctIndex: 2, explanation: "The legendary rock band formed in Sydney in 1973." },
  { text: "Who sang 'I Will Always Love You' in the movie The Bodyguard?", options: ["Dolly Parton", "Celine Dion", "Whitney Houston", "Mariah Carey"], correctIndex: 2, explanation: "Whitney's version became one of the biggest hits ever." },
  { text: "What was Elvis Presley's first number one hit in the US?", options: ["Hound Dog", "Heartbreak Hotel", "Jailhouse Rock", "Love Me Tender"], correctIndex: 1, explanation: "Heartbreak Hotel was released in 1956." },
  { text: "Which artist released 'Blinding Lights' in 2019?", options: ["Drake", "The Weeknd", "Post Malone", "Bruno Mars"], correctIndex: 1, explanation: "The Weeknd's hit became the longest-charting song on Billboard." },
  { text: "Who wrote the song 'Hallelujah'?", options: ["Jeff Buckley", "Leonard Cohen", "Rufus Wainwright", "Bob Dylan"], correctIndex: 1, explanation: "Leonard Cohen wrote it; Buckley's version is also famous." },
  { text: "Which band is known for the hit 'Don't Stop Believin'?", options: ["Journey", "Foreigner", "Boston", "Toto"], correctIndex: 0, explanation: "Journey released this karaoke classic in 1981." },
  { text: "Who is the 'Rocket Man'?", options: ["David Bowie", "Elton John", "Billy Joel", "Paul McCartney"], correctIndex: 1, explanation: "Elton John released 'Rocket Man' in 1972." },
  { text: "What is the real name of Lady Gaga?", options: ["Stefani Germanotta", "Robyn Fenty", "Katy Hudson", "Alecia Moore"], correctIndex: 0, explanation: "She adopted her stage name from the Queen song 'Radio Ga Ga'." },
  { text: "Which band released 'Dark Side of the Moon'?", options: ["Genesis", "The Doors", "Pink Floyd", "Yes"], correctIndex: 2, explanation: "It's one of the most critically acclaimed rock albums ever." },
  { text: "Who was the lead singer of Nirvana?", options: ["Dave Grohl", "Kurt Cobain", "Eddie Vedder", "Chris Cornell"], correctIndex: 1, explanation: "Cobain was the face of the 90s grunge movement." },
  { text: "Which song begins with 'Is this the real life? Is this just fantasy?'", options: ["Imagine", "Bohemian Rhapsody", "Hotel California", "Stayin' Alive"], correctIndex: 1, explanation: "One of the most recognizable opening lines in music history." }
];

const GENERAL_POOL: Partial<Question>[] = [
  { text: "What is the capital city of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correctIndex: 2, explanation: "Canberra was chosen as the capital in 1908 as a compromise." },
  { text: "How many continents are there on Earth?", options: ["5", "6", "7", "8"], correctIndex: 2, explanation: "Asia, Africa, N. America, S. America, Antarctica, Europe, Australia." },
  { text: "Which planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Saturn"], correctIndex: 1, explanation: "Mars gets its red color from iron oxide (rust) on its surface." },
  { text: "Who painted the Mona Lisa?", options: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"], correctIndex: 2, explanation: "It was painted in the early 16th century." },
  { text: "What is the largest ocean on Earth?", options: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"], correctIndex: 3, explanation: "The Pacific covers about 30% of the Earth's surface." },
  { text: "In which year did the Titanic sink?", options: ["1908", "1912", "1915", "1920"], correctIndex: 1, explanation: "It hit an iceberg on its maiden voyage in April 1912." },
  { text: "What is the chemical symbol for Gold?", options: ["Go", "Gd", "Au", "Ag"], correctIndex: 2, explanation: "Au comes from the Latin word 'Aurum'." },
  { text: "Which country gifted the Statue of Liberty to the USA?", options: ["UK", "France", "Germany", "Italy"], correctIndex: 1, explanation: "It was a gift to celebrate the centennial of the Declaration of Independence." },
  { text: "How many bones are there in the adult human body?", options: ["156", "206", "256", "306"], correctIndex: 1, explanation: "Adults have 206, while babies are born with about 270." },
  { text: "What is the tallest mountain in the world?", options: ["K2", "Mount Kilimanjaro", "Mount Everest", "Mount Fuji"], correctIndex: 2, explanation: "It stands at 8,848 meters (29,029 ft) above sea level." },
  { text: "Which gas do plants absorb from the atmosphere?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], correctIndex: 2, explanation: "Plants use CO2 for photosynthesis." },
  { text: "Who was the first man to walk on the moon?", options: ["Buzz Aldrin", "Yuri Gagarin", "Neil Armstrong", "John Glenn"], correctIndex: 2, explanation: "Armstrong walked on the moon in July 1969." },
  { text: "What is the smallest country in the world?", options: ["Monaco", "Nauru", "Vatican City", "San Marino"], correctIndex: 2, explanation: "Vatican City is an enclave within Rome, Italy." },
  { text: "How many colors are in a rainbow?", options: ["5", "6", "7", "8"], correctIndex: 2, explanation: "Roy G. Biv: Red, Orange, Yellow, Green, Blue, Indigo, Violet." },
  { text: "What is the longest river in the world?", options: ["Amazon River", "Nile River", "Yangtze River", "Mississippi River"], correctIndex: 1, explanation: "The Nile is generally considered the longest at ~6,650 km." },
  { text: "Who wrote 'Romeo and Juliet'?", options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"], correctIndex: 1, explanation: "The famous tragedy was written around 1595." },
  { text: "What is the main ingredient in Hummus?", options: ["Lentils", "Chickpeas", "Black Beans", "Kidney Beans"], correctIndex: 1, explanation: "Chickpeas are blended with tahini, oil, and lemon." },
  { text: "How many players are on a standard soccer team?", options: ["9", "10", "11", "12"], correctIndex: 2, explanation: "There are 11 players including the goalkeeper." },
  { text: "What is the hardest natural substance on Earth?", options: ["Gold", "Iron", "Diamond", "Platinum"], correctIndex: 2, explanation: "Diamonds are made of pure carbon in a crystal structure." },
  { text: "Which year did the Berlin Wall fall?", options: ["1987", "1989", "1991", "1993"], correctIndex: 1, explanation: "The wall fell on November 9, 1989." },
  { text: "How many seconds are in an hour?", options: ["360", "3600", "600", "60"], correctIndex: 1, explanation: "60 seconds per minute x 60 minutes = 3600." },
  { text: "Which animal is the largest mammal in the world?", options: ["Elephant", "Blue Whale", "Giraffe", "Hippopotamus"], correctIndex: 1, explanation: "Blue whales can grow up to 100 feet long." },
  { text: "What is the largest country in the world by area?", options: ["USA", "China", "Russia", "Canada"], correctIndex: 2, explanation: "Russia covers more than 17 million square kilometers." },
  { text: "Who invented the light bulb?", options: ["Nikola Tesla", "Thomas Edison", "Alexander Graham Bell", "Albert Einstein"], correctIndex: 1, explanation: "Edison patented the first commercially successful light bulb." },
  { text: "What is the national flower of England?", options: ["Rose", "Tulip", "Lily", "Daisy"], correctIndex: 0, explanation: "The Tudor Rose is the floral emblem of England." }
];

export const ALL_QUESTIONS = {
  [Category.DISNEY]: DISNEY_POOL,
  [Category.MUSIC]: MUSIC_POOL,
  [Category.GENERAL]: GENERAL_POOL,
};
