import { Question, Category } from './types';

export const questionsPool: Question[] = [
  // ==========================================
  // DISNEY CATEGORY
  // ==========================================
  { id: 'd1', category: Category.DISNEY, text: "In 'The Lion King', what is the name of Simba's mother?", options: ["Nala", "Sarabi", "Zira", "Shenzi"], correctIndex: 1, explanation: "Sarabi is Mufasa's queen.", isBonus: false },
  { id: 'd2', category: Category.DISNEY, text: "Which Disney Princess has a raccoon sidekick?", options: ["Pocahontas", "Snow White", "Merida", "Rapunzel"], correctIndex: 0, explanation: "Meeko is the raccoon.", isBonus: false },
  { id: 'd3', category: Category.DISNEY, text: "Name the toy store in 'Toy Story 2'.", options: ["Al's Toy Barn", "Toys R Us", "Pizza Planet", "Sid's Toys"], correctIndex: 0, explanation: "Al McWhiggin owns it.", isBonus: false },
  { id: 'd4', category: Category.DISNEY, text: "First Disney character on the Walk of Fame?", options: ["Snow White", "Mickey Mouse", "Donald Duck", "Walt"], correctIndex: 1, explanation: "Mickey got it in 1978.", isBonus: true },
  { id: 'd5', category: Category.DISNEY, text: "Frozen's snow monster name?", options: ["Snowball", "Marshmallow", "Olaf", "Slushy"], correctIndex: 1, explanation: "Marshmallow guards the palace.", isBonus: false },
  { id: 'd6', category: Category.DISNEY, text: "Setting of 'Princess and the Frog'?", options: ["Paris", "New York", "New Orleans", "London"], correctIndex: 2, explanation: "It's New Orleans.", isBonus: false },
  { id: 'd7', category: Category.DISNEY, text: "Hakuna Matata means?", options: ["No worries", "Good luck", "Live life", "Be happy"], correctIndex: 0, explanation: "No worries!", isBonus: false },
  { id: 'd8', category: Category.DISNEY, text: "Song 'You Can Fly' is in?", options: ["Dumbo", "Peter Pan", "Aladdin", "Mary Poppins"], correctIndex: 1, explanation: "Peter Pan.", isBonus: false },
  { id: 'd9', category: Category.DISNEY, text: "Pub name in Tangled?", options: ["Snuggly Duckling", "Rusty Horseshoe", "Poisoned Apple", "Golden Goose"], correctIndex: 0, explanation: "The Snuggly Duckling.", isBonus: false },
  { id: 'd10', category: Category.DISNEY, text: "Incredibles fashion designer?", options: ["Coco", "Edna Mode", "Cruella", "Medusa"], correctIndex: 1, explanation: "Edna Mode. No capes!", isBonus: false },
  { id: 'd11', category: Category.DISNEY, text: "Kingdom in Frozen?", options: ["Genovia", "Arendelle", "Corona", "Atlantica"], correctIndex: 1, explanation: "Arendelle.", isBonus: false },
  { id: 'd12', category: Category.DISNEY, text: "Who sings 'Kiss the Girl'?", options: ["Sebastian", "Flounder", "Scuttle", "Triton"], correctIndex: 0, explanation: "Sebastian the crab.", isBonus: false },
  { id: 'd13', category: Category.DISNEY, text: "Sulley's full name in Monsters Inc?", options: ["James P. Sullivan", "John P. Sullivan", "Jim S. Sullivan", "Jack P. Sullivan"], correctIndex: 0, explanation: "James P. Sullivan.", isBonus: false },
  { id: 'd14', category: Category.DISNEY, text: "Jafar turns into what animal?", options: ["Cobra", "Dragon", "Lion", "Bear"], correctIndex: 0, explanation: "A giant Cobra.", isBonus: false },
  { id: 'd15', category: Category.DISNEY, text: "First Disney princess?", options: ["Cinderella", "Snow White", "Aurora", "Belle"], correctIndex: 1, explanation: "Snow White (1937).", isBonus: false },
  { id: 'd16', category: Category.DISNEY, text: "Teacup's name in Beauty/Beast?", options: ["Chip", "Dale", "Pip", "Spot"], correctIndex: 0, explanation: "Chip.", isBonus: false },
  { id: 'd17', category: Category.DISNEY, text: "What animal is Baloo?", options: ["Grizzly Bear", "Sloth Bear", "Polar Bear", "Panda"], correctIndex: 1, explanation: "Sloth Bear.", isBonus: true },
  { id: 'd18', category: Category.DISNEY, text: "Movie with 'Circle of Life'?", options: ["Tarzan", "The Lion King", "Mulan", "Pocahontas"], correctIndex: 1, explanation: "The Lion King.", isBonus: false },
  { id: 'd19', category: Category.DISNEY, text: "Mulan's dragon sidekick?", options: ["Mushu", "Sisu", "Spyro", "Toothless"], correctIndex: 0, explanation: "Mushu.", isBonus: false },
  { id: 'd20', category: Category.DISNEY, text: "Dory's remembered address?", options: ["42 Wallaby Way", "221B Baker St", "742 Evergreen", "31 Spooner St"], correctIndex: 0, explanation: "42 Wallaby Way, Sydney.", isBonus: false },
  { id: 'd21', category: Category.DISNEY, text: "Villian in 101 Dalmatians?", options: ["Ursula", "Cruella de Vil", "Maleficent", "Yzma"], correctIndex: 1, explanation: "Cruella de Vil.", isBonus: false },
  { id: 'd22', category: Category.DISNEY, text: "Robot in Wall-E?", options: ["Wall-E", "Eve", "M-O", "Auto"], correctIndex: 0, explanation: "Wall-E.", isBonus: false },
  { id: 'd23', category: Category.DISNEY, text: "Aladdin's Monkey?", options: ["Abu", "Iago", "Rajah", "Sultan"], correctIndex: 0, explanation: "Abu.", isBonus: false },
  { id: 'd24', category: Category.DISNEY, text: "How many brothers does Hans have in Frozen?", options: ["12", "7", "9", "3"], correctIndex: 0, explanation: "12 older brothers.", isBonus: true },
  { id: 'd25', category: Category.DISNEY, text: "Who is the demigod in Moana?", options: ["Maui", "Te Fiti", "Tamatoa", "Heihei"], correctIndex: 0, explanation: "Maui.", isBonus: false },
  { id: 'd26', category: Category.DISNEY, text: "Name of the skunk in Bambi?", options: ["Flower", "Stinky", "Rose", "Petunia"], correctIndex: 0, explanation: "Flower.", isBonus: false },
  { id: 'd27', category: Category.DISNEY, text: "Lightning McQueen's racing number?", options: ["95", "86", "43", "53"], correctIndex: 0, explanation: "95.", isBonus: false },
  { id: 'd28', category: Category.DISNEY, text: "Who voices the Genie (1992)?", options: ["Robin Williams", "Will Smith", "Eddie Murphy", "Jim Carrey"], correctIndex: 0, explanation: "Robin Williams.", isBonus: false },
  { id: 'd29', category: Category.DISNEY, text: "What does Ariel use to comb her hair?", options: ["Dinglehopper", "Snarfblatt", "Thingamabob", "Whosit"], correctIndex: 0, explanation: "A Dinglehopper (fork).", isBonus: false },
  { id: 'd30', category: Category.DISNEY, text: "Villain in Hercules?", options: ["Hades", "Zeus", "Scar", "Jafar"], correctIndex: 0, explanation: "Hades.", isBonus: false },
  { id: 'd31', category: Category.DISNEY, text: "Who is the nanny in Peter Pan?", options: ["Nana", "Coco", "Lady", "Perdita"], correctIndex: 0, explanation: "Nana the dog.", isBonus: false },
  { id: 'd32', category: Category.DISNEY, text: "Rapunzel's weapon of choice?", options: ["Frying Pan", "Sword", "Bow", "Magic Hair"], correctIndex: 0, explanation: "A Frying Pan.", isBonus: false },
  { id: 'd33', category: Category.DISNEY, text: "Name of the daycare in Toy Story 3?", options: ["Sunnyside", "Happy Days", "Playtime", "Kinder"], correctIndex: 0, explanation: "Sunnyside Daycare.", isBonus: false },
  { id: 'd34', category: Category.DISNEY, text: "Who raised Tarzan?", options: ["Gorillas", "Wolves", "Bears", "Tigers"], correctIndex: 0, explanation: "Gorillas (Kala).", isBonus: false },
  { id: 'd35', category: Category.DISNEY, text: "Sleeping Beauty's real name?", options: ["Aurora", "Belle", "Ariel", "Tiana"], correctIndex: 0, explanation: "Princess Aurora.", isBonus: false },
  { id: 'd36', category: Category.DISNEY, text: "Who is the main character in Coco?", options: ["Miguel", "Hector", "Dante", "Ernesto"], correctIndex: 0, explanation: "Miguel.", isBonus: false },
  { id: 'd37', category: Category.DISNEY, text: "Lilo's sister's name?", options: ["Nani", "Nina", "Mina", "Lana"], correctIndex: 0, explanation: "Nani.", isBonus: false },
  { id: 'd38', category: Category.DISNEY, text: "What kind of fish is Nemo?", options: ["Clownfish", "Blue Tang", "Goldfish", "Shark"], correctIndex: 0, explanation: "Clownfish.", isBonus: false },
  { id: 'd39', category: Category.DISNEY, text: "Who is the fashionista in Minnie's Bow-Toons?", options: ["Daisy", "Clarabelle", "Cuckoo-Loca", "Minnie"], correctIndex: 2, explanation: "Cuckoo-Loca.", isBonus: true },
  { id: 'd40', category: Category.DISNEY, text: "Name of the high school in High School Musical?", options: ["East High", "West High", "North High", "Wildcat High"], correctIndex: 0, explanation: "East High School.", isBonus: false },
  { id: 'd41', category: Category.DISNEY, text: "Princess with ice powers?", options: ["Elsa", "Anna", "Rapunzel", "Merida"], correctIndex: 0, explanation: "Elsa.", isBonus: false },
  { id: 'd42', category: Category.DISNEY, text: "Who loves 'Warm Hugs'?", options: ["Olaf", "Sven", "Kristoff", "Hans"], correctIndex: 0, explanation: "Olaf.", isBonus: false },
  { id: 'd43', category: Category.DISNEY, text: "Mike Wazowski's best friend?", options: ["Sulley", "Randall", "Boo", "Roz"], correctIndex: 0, explanation: "Sulley.", isBonus: false },
  { id: 'd44', category: Category.DISNEY, text: "Captain Hook is afraid of?", options: ["Crocodile", "Shark", "Whale", "Octopus"], correctIndex: 0, explanation: "The Tick-Tock Crocodile.", isBonus: false },
  { id: 'd45', category: Category.DISNEY, text: "Color of the genie?", options: ["Blue", "Red", "Green", "Purple"], correctIndex: 0, explanation: "Blue.", isBonus: false },
  { id: 'd46', category: Category.DISNEY, text: "Prince in Little Mermaid?", options: ["Eric", "Phillip", "Charming", "Adam"], correctIndex: 0, explanation: "Prince Eric.", isBonus: false },
  { id: 'd47', category: Category.DISNEY, text: "Who says 'To Infinity and Beyond'?", options: ["Buzz", "Woody", "Jessie", "Rex"], correctIndex: 0, explanation: "Buzz Lightyear.", isBonus: false },
  { id: 'd48', category: Category.DISNEY, text: "What does Cinderella lose?", options: ["Glass Slipper", "Crown", "Necklace", "Glove"], correctIndex: 0, explanation: "Glass Slipper.", isBonus: false },
  { id: 'd49', category: Category.DISNEY, text: "Main emotion in Inside Out?", options: ["Joy", "Sadness", "Anger", "Fear"], correctIndex: 0, explanation: "Joy is the leader.", isBonus: false },
  { id: 'd50', category: Category.DISNEY, text: "Who killed Mufasa?", options: ["Scar", "Zira", "Hyenas", "Simba"], correctIndex: 0, explanation: "Scar.", isBonus: false },

  // ==========================================
  // MUSIC CATEGORY
  // ==========================================
  { id: 'm1', category: Category.MUSIC, text: "King of Pop?", options: ["Elvis", "Michael Jackson", "Prince", "Freddie"], correctIndex: 1, explanation: "MJ is the King of Pop.", isBonus: false },
  { id: 'm2', category: Category.MUSIC, text: "Released 'Abbey Road'?", options: ["Stones", "The Who", "The Beatles", "Floyd"], correctIndex: 2, explanation: "The Beatles.", isBonus: false },
  { id: 'm3', category: Category.MUSIC, text: "Started as Hannah Montana?", options: ["Selena", "Demi", "Miley Cyrus", "Ariana"], correctIndex: 2, explanation: "Miley Cyrus.", isBonus: false },
  { id: 'm4', category: Category.MUSIC, text: "Sang 'Shape of You'?", options: ["Bieber", "Styles", "Ed Sheeran", "Mendes"], correctIndex: 2, explanation: "Ed Sheeran.", isBonus: false },
  { id: 'm5', category: Category.MUSIC, text: "NOT a Spice Girl?", options: ["Scary", "Sporty", "Ginger", "Salt"], correctIndex: 3, explanation: "Salt Spice doesn't exist.", isBonus: false },
  { id: 'm6', category: Category.MUSIC, text: "Violin strings count?", options: ["4", "6", "5", "3"], correctIndex: 0, explanation: "Four strings.", isBonus: true },
  { id: 'm7', category: Category.MUSIC, text: "2024 Super Bowl performer?", options: ["Rihanna", "Usher", "Weeknd", "Beyonce"], correctIndex: 1, explanation: "Usher.", isBonus: false },
  { id: 'm8', category: Category.MUSIC, text: "Band named after Foo Fighter?", options: ["Foo Fighters", "Nirvana", "Pearl Jam", "U2"], correctIndex: 0, explanation: "Foo Fighters.", isBonus: false },
  { id: 'm9', category: Category.MUSIC, text: "The Material Girl?", options: ["Cyndi", "Madonna", "Cher", "Britney"], correctIndex: 1, explanation: "Madonna.", isBonus: false },
  { id: 'm10', category: Category.MUSIC, text: "Wrote Bohemian Rhapsody?", options: ["May", "Mercury", "Taylor", "Deacon"], correctIndex: 1, explanation: "Freddie Mercury.", isBonus: false },
  { id: 'm11', category: Category.MUSIC, text: "Who sings 'Rolling in the Deep'?", options: ["Adele", "Sia", "Katy Perry", "Gaga"], correctIndex: 0, explanation: "Adele.", isBonus: false },
  { id: 'm12', category: Category.MUSIC, text: "Lizzo plays which instrument?", options: ["Flute", "Piano", "Guitar", "Drums"], correctIndex: 0, explanation: "She is a flautist.", isBonus: false },
  { id: 'm13', category: Category.MUSIC, text: "Lead singer of Coldplay?", options: ["Chris Martin", "Thom Yorke", "Bono", "Sting"], correctIndex: 0, explanation: "Chris Martin.", isBonus: false },
  { id: 'm14', category: Category.MUSIC, text: "First video on MTV?", options: ["Video Killed the Radio Star", "Thriller", "Take on Me", "Money for Nothing"], correctIndex: 0, explanation: "Video Killed the Radio Star.", isBonus: true },
  { id: 'm15', category: Category.MUSIC, text: "Lady Gaga's fans are called?", options: ["Little Monsters", "KatyCats", "Barbz", "Swifties"], correctIndex: 0, explanation: "Little Monsters.", isBonus: false },
  { id: 'm16', category: Category.MUSIC, text: "Eminem's real name?", options: ["Marshall Mathers", "Curtis Jackson", "Calvin Broadus", "Shawn Carter"], correctIndex: 0, explanation: "Marshall Mathers.", isBonus: false },
  { id: 'm17', category: Category.MUSIC, text: "Whitney Houston movie hit?", options: ["I Will Always Love You", "Jolene", "Respect", "Hero"], correctIndex: 0, explanation: "I Will Always Love You.", isBonus: false },
  { id: 'm18', category: Category.MUSIC, text: "Nirvana's big hit?", options: ["Smells Like Teen Spirit", "Wonderwall", "Creep", "Black Hole Sun"], correctIndex: 0, explanation: "Smells Like Teen Spirit.", isBonus: false },
  { id: 'm19', category: Category.MUSIC, text: "The Rocket Man?", options: ["Elton John", "David Bowie", "Billy Joel", "Prince"], correctIndex: 0, explanation: "Elton John.", isBonus: false },
  { id: 'm20', category: Category.MUSIC, text: "One Direction member?", options: ["Harry Styles", "Justin Timberlake", "Nick Jonas", "Shawn Mendes"], correctIndex: 0, explanation: "Harry Styles.", isBonus: false },
  { id: 'm21', category: Category.MUSIC, text: "Queen of Soul?", options: ["Aretha Franklin", "Diana Ross", "Tina Turner", "Etta James"], correctIndex: 0, explanation: "Aretha Franklin.", isBonus: false },
  { id: 'm22', category: Category.MUSIC, text: "Album 'Lemonade' artist?", options: ["Beyoncé", "Rihanna", "Solange", "Nicki"], correctIndex: 0, explanation: "Beyoncé.", isBonus: false },
  { id: 'm23', category: Category.MUSIC, text: "Beatle assassinated in 1980?", options: ["John Lennon", "Paul McCartney", "George Harrison", "Ringo"], correctIndex: 0, explanation: "John Lennon.", isBonus: false },
  { id: 'm24', category: Category.MUSIC, text: "Sings 'Bad Guy'?", options: ["Billie Eilish", "Dua Lipa", "Olivia Rodrigo", "Halsey"], correctIndex: 0, explanation: "Billie Eilish.", isBonus: false },
  { id: 'm25', category: Category.MUSIC, text: "Bob Marley's genre?", options: ["Reggae", "Jazz", "Blues", "Rock"], correctIndex: 0, explanation: "Reggae.", isBonus: false },
  { id: 'm26', category: Category.MUSIC, text: "U2 Lead Singer?", options: ["Bono", "Edge", "Adam", "Larry"], correctIndex: 0, explanation: "Bono.", isBonus: false },
  { id: 'm27', category: Category.MUSIC, text: "Bit a bat's head off?", options: ["Ozzy Osbourne", "Alice Cooper", "Gene Simmons", "Manson"], correctIndex: 0, explanation: "Ozzy Osbourne.", isBonus: true },
  { id: 'm28', category: Category.MUSIC, text: "K-Pop group?", options: ["BTS", "NSYNC", "Backstreet Boys", "One Direction"], correctIndex: 0, explanation: "BTS.", isBonus: false },
  { id: 'm29', category: Category.MUSIC, text: "'Thriller' singer?", options: ["Michael Jackson", "Prince", "Stevie Wonder", "Lionel Richie"], correctIndex: 0, explanation: "Michael Jackson.", isBonus: false },
  { id: 'm30', category: Category.MUSIC, text: "Country singer 'Jolene'?", options: ["Dolly Parton", "Reba", "Carrie Underwood", "Shania"], correctIndex: 0, explanation: "Dolly Parton.", isBonus: false },
  { id: 'm31', category: Category.MUSIC, text: "Drummer for The Beatles?", options: ["Ringo Starr", "John Bonham", "Keith Moon", "Charlie Watts"], correctIndex: 0, explanation: "Ringo Starr.", isBonus: false },
  { id: 'm32', category: Category.MUSIC, text: "'Purple Rain' artist?", options: ["Prince", "Hendrix", "Bowie", "Jagger"], correctIndex: 0, explanation: "Prince.", isBonus: false },
  { id: 'm33', category: Category.MUSIC, text: "Rapper 'Gold Digger'?", options: ["Kanye West", "Jay-Z", "Drake", "50 Cent"], correctIndex: 0, explanation: "Kanye West.", isBonus: false },
  { id: 'm34', category: Category.MUSIC, text: "Singer 'Hello' (2015)?", options: ["Adele", "Lionel Richie", "Sam Smith", "Sia"], correctIndex: 0, explanation: "Adele.", isBonus: false },
  { id: 'm35', category: Category.MUSIC, text: "Band 'Yellow Submarine'?", options: ["The Beatles", "The Rolling Stones", "The Beach Boys", "The Kinks"], correctIndex: 0, explanation: "The Beatles.", isBonus: false },
  { id: 'm36', category: Category.MUSIC, text: "Sings 'Shake it Off'?", options: ["Taylor Swift", "Katy Perry", "Ariana Grande", "Selena Gomez"], correctIndex: 0, explanation: "Taylor Swift.", isBonus: false },
  { id: 'm37', category: Category.MUSIC, text: "Who is Ziggy Stardust?", options: ["David Bowie", "Elton John", "Freddie Mercury", "Iggy Pop"], correctIndex: 0, explanation: "David Bowie.", isBonus: true },
  { id: 'm38', category: Category.MUSIC, text: "Sings 'Uptown Funk'?", options: ["Bruno Mars", "Justin Timberlake", "Pharrell", "Weeknd"], correctIndex: 0, explanation: "Bruno Mars (with Mark Ronson).", isBonus: false },
  { id: 'm39', category: Category.MUSIC, text: "'Piano Man' singer?", options: ["Billy Joel", "Elton John", "Bruce Springsteen", "Tom Petty"], correctIndex: 0, explanation: "Billy Joel.", isBonus: false },
  { id: 'm40', category: Category.MUSIC, text: "Band 'Hotel California'?", options: ["The Eagles", "Fleetwood Mac", "Lynyrd Skynyrd", "Chicago"], correctIndex: 0, explanation: "The Eagles.", isBonus: false },
  { id: 'm41', category: Category.MUSIC, text: "Sings 'Single Ladies'?", options: ["Beyoncé", "Rihanna", "Ciara", "Alicia Keys"], correctIndex: 0, explanation: "Beyoncé.", isBonus: false },
  { id: 'm42', category: Category.MUSIC, text: "Rapper 'Lose Yourself'?", options: ["Eminem", "Dr. Dre", "Snoop Dogg", "Tupac"], correctIndex: 0, explanation: "Eminem.", isBonus: false },
  { id: 'm43', category: Category.MUSIC, text: "Sings 'Rehab'?", options: ["Amy Winehouse", "Adele", "Duffy", "Lana Del Rey"], correctIndex: 0, explanation: "Amy Winehouse.", isBonus: false },
  { id: 'm44', category: Category.MUSIC, text: "Band 'Wonderwall'?", options: ["Oasis", "Blur", "Radiohead", "Pulp"], correctIndex: 0, explanation: "Oasis.", isBonus: false },
  { id: 'm45', category: Category.MUSIC, text: "Sings 'Baby One More Time'?", options: ["Britney Spears", "Christina Aguilera", "Jessica Simpson", "Mandy Moore"], correctIndex: 0, explanation: "Britney Spears.", isBonus: false },
  { id: 'm46', category: Category.MUSIC, text: "Sings 'I Will Survive'?", options: ["Gloria Gaynor", "Donna Summer", "Diana Ross", "Chaka Khan"], correctIndex: 0, explanation: "Gloria Gaynor.", isBonus: false },
  { id: 'm47', category: Category.MUSIC, text: "Sings 'Like a Virgin'?", options: ["Madonna", "Cyndi Lauper", "Tina Turner", "Cher"], correctIndex: 0, explanation: "Madonna.", isBonus: false },
  { id: 'm48', category: Category.MUSIC, text: "Band 'Bohemian Rhapsody'?", options: ["Queen", "Led Zeppelin", "Pink Floyd", "The Who"], correctIndex: 0, explanation: "Queen.", isBonus: false },
  { id: 'm49', category: Category.MUSIC, text: "Sings 'Hips Don't Lie'?", options: ["Shakira", "JLo", "Beyoncé", "Rihanna"], correctIndex: 0, explanation: "Shakira.", isBonus: false },
  { id: 'm50', category: Category.MUSIC, text: "Sings 'Sweet Caroline'?", options: ["Neil Diamond", "Elvis", "Tom Jones", "Frank Sinatra"], correctIndex: 0, explanation: "Neil Diamond.", isBonus: false },

  // ==========================================
  // GENERAL KNOWLEDGE CATEGORY
  // ==========================================
  { id: 'g1', category: Category.GENERAL, text: "Red Planet?", options: ["Venus", "Jupiter", "Mars", "Saturn"], correctIndex: 2, explanation: "Mars.", isBonus: false },
  { id: 'g2', category: Category.GENERAL, text: "Octopus hearts?", options: ["1", "2", "3", "4"], correctIndex: 2, explanation: "Three hearts.", isBonus: true },
  { id: 'g3', category: Category.GENERAL, text: "Capital of France?", options: ["Rome", "Madrid", "Berlin", "Paris"], correctIndex: 3, explanation: "Paris.", isBonus: false },
  { id: 'g4', category: Category.GENERAL, text: "Symbol 'O'?", options: ["Gold", "Oxygen", "Osmium", "Olive"], correctIndex: 1, explanation: "Oxygen.", isBonus: false },
  { id: 'g5', category: Category.GENERAL, text: "Days in leap year?", options: ["365", "364", "366", "367"], correctIndex: 2, explanation: "366 days.", isBonus: false },
  { id: 'g6', category: Category.GENERAL, text: "Painted Mona Lisa?", options: ["Van Gogh", "Picasso", "Da Vinci", "Michelangelo"], correctIndex: 2, explanation: "Da Vinci.", isBonus: false },
  { id: 'g7', category: Category.GENERAL, text: "Fastest land animal?", options: ["Lion", "Gazelle", "Cheetah", "Leopard"], correctIndex: 2, explanation: "Cheetah.", isBonus: false },
  { id: 'g8', category: Category.GENERAL, text: "Largest Ocean?", options: ["Atlantic", "Indian", "Arctic", "Pacific"], correctIndex: 3, explanation: "Pacific.", isBonus: false },
  { id: 'g9', category: Category.GENERAL, text: "Hardest natural substance?", options: ["Gold", "Iron", "Diamond", "Platinum"], correctIndex: 2, explanation: "Diamond.", isBonus: false },
  { id: 'g10', category: Category.GENERAL, text: "Chemical symbol for Gold?", options: ["Au", "Ag", "Fe", "Go"], correctIndex: 0, explanation: "Au (Aurum).", isBonus: true },
  { id: 'g11', category: Category.GENERAL, text: "Population Champ?", options: ["USA", "India", "China", "Russia"], correctIndex: 1, explanation: "India.", isBonus: false },
  { id: 'g12', category: Category.GENERAL, text: "UK Currency?", options: ["Euro", "Dollar", "Pound", "Franc"], correctIndex: 2, explanation: "Pound Sterling.", isBonus: false },
  { id: 'g13', category: Category.GENERAL, text: "Human bones count?", options: ["206", "195", "215", "300"], correctIndex: 0, explanation: "206.", isBonus: false },
  { id: 'g14', category: Category.GENERAL, text: "Tallest Mountain?", options: ["K2", "Kilimanjaro", "Everest", "Fuji"], correctIndex: 2, explanation: "Mount Everest.", isBonus: false },
  { id: 'g15', category: Category.GENERAL, text: "Planet closest to Sun?", options: ["Venus", "Mercury", "Earth", "Mars"], correctIndex: 1, explanation: "Mercury.", isBonus: false },
  { id: 'g16', category: Category.GENERAL, text: "Romeo & Juliet author?", options: ["Dickens", "Austen", "Shakespeare", "Twain"], correctIndex: 2, explanation: "Shakespeare.", isBonus: false },
  { id: 'g17', category: Category.GENERAL, text: "Freezing point Celsius?", options: ["100", "0", "-10", "32"], correctIndex: 1, explanation: "0°C.", isBonus: false },
  { id: 'g18', category: Category.GENERAL, text: "Largest Mammal?", options: ["Elephant", "Blue Whale", "Giraffe", "Hippo"], correctIndex: 1, explanation: "Blue Whale.", isBonus: false },
  { id: 'g19', category: Category.GENERAL, text: "Number of continents?", options: ["5", "6", "7", "8"], correctIndex: 2, explanation: "7.", isBonus: false },
  { id: 'g20', category: Category.GENERAL, text: "Plants absorb?", options: ["Oxygen", "CO2", "Nitrogen", "Hydrogen"], correctIndex: 1, explanation: "Carbon Dioxide.", isBonus: false },
  { id: 'g21', category: Category.GENERAL, text: "Pizza invented in?", options: ["France", "USA", "Italy", "Greece"], correctIndex: 2, explanation: "Italy.", isBonus: false },
  { id: 'g22', category: Category.GENERAL, text: "Guacamole ingredient?", options: ["Tomato", "Avocado", "Onion", "Pepper"], correctIndex: 1, explanation: "Avocado.", isBonus: false },
  { id: 'g23', category: Category.GENERAL, text: "Soccer players on field?", options: ["10", "11", "12", "9"], correctIndex: 1, explanation: "11.", isBonus: false },
  { id: 'g24', category: Category.GENERAL, text: "First moon walker?", options: ["Aldrin", "Gagarin", "Armstrong", "Collins"], correctIndex: 2, explanation: "Neil Armstrong.", isBonus: false },
  { id: 'g25', category: Category.GENERAL, text: "Smallest country?", options: ["Monaco", "Vatican City", "San Marino", "Malta"], correctIndex: 1, explanation: "Vatican City.", isBonus: false },
  { id: 'g26', category: Category.GENERAL, text: "WW2 ended in?", options: ["1943", "1944", "1945", "1946"], correctIndex: 2, explanation: "1945.", isBonus: false },
  { id: 'g27', category: Category.GENERAL, text: "Olympic rings colors?", options: ["Blue,Yel,Blk,Grn,Red", "Red,Wht,Blu", "Blu,Red,Prp", "Blk,Wht,Red"], correctIndex: 0, explanation: "Blue, Yellow, Black, Green, Red.", isBonus: true },
  { id: 'g28', category: Category.GENERAL, text: "Longest river?", options: ["Amazon", "Nile", "Yangtze", "Mississippi"], correctIndex: 1, explanation: "Nile (or Amazon debated).", isBonus: false },
  { id: 'g29', category: Category.GENERAL, text: "Ship of the Desert?", options: ["Horse", "Camel", "Elephant", "Donkey"], correctIndex: 1, explanation: "Camel.", isBonus: false },
  { id: 'g30', category: Category.GENERAL, text: "Scotland animal?", options: ["Lion", "Eagle", "Unicorn", "Stag"], correctIndex: 2, explanation: "Unicorn.", isBonus: true },
  { id: 'g31', category: Category.GENERAL, text: "Capital of Spain?", options: ["Barcelona", "Madrid", "Seville", "Valencia"], correctIndex: 1, explanation: "Madrid.", isBonus: false },
  { id: 'g32', category: Category.GENERAL, text: "H2O is?", options: ["Salt", "Water", "Air", "Gold"], correctIndex: 1, explanation: "Water.", isBonus: false },
  { id: 'g33', category: Category.GENERAL, text: "Colors in rainbow?", options: ["5", "6", "7", "8"], correctIndex: 2, explanation: "7.", isBonus: false },
  { id: 'g34', category: Category.GENERAL, text: "Spider legs count?", options: ["6", "8", "10", "12"], correctIndex: 1, explanation: "8.", isBonus: false },
  { id: 'g35', category: Category.GENERAL, text: "Capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correctIndex: 2, explanation: "Canberra.", isBonus: false },
  { id: 'g36', category: Category.GENERAL, text: "Start of WW1?", options: ["1912", "1914", "1916", "1918"], correctIndex: 1, explanation: "1914.", isBonus: false },
  { id: 'g37', category: Category.GENERAL, text: "USA states count?", options: ["48", "50", "52", "51"], correctIndex: 1, explanation: "50.", isBonus: false },
  { id: 'g38', category: Category.GENERAL, text: "Boiling point Celsius?", options: ["90", "100", "110", "212"], correctIndex: 1, explanation: "100°C.", isBonus: false },
  { id: 'g39', category: Category.GENERAL, text: "Largest planet?", options: ["Earth", "Mars", "Jupiter", "Saturn"], correctIndex: 2, explanation: "Jupiter.", isBonus: false },
  { id: 'g40', category: Category.GENERAL, text: "Current UK Monarch?", options: ["Charles III", "William", "Elizabeth II", "Harry"], correctIndex: 0, explanation: "King Charles III.", isBonus: false },
  { id: 'g41', category: Category.GENERAL, text: "Currency of Japan?", options: ["Yuan", "Won", "Yen", "Dollar"], correctIndex: 2, explanation: "Yen.", isBonus: false },
  { id: 'g42', category: Category.GENERAL, text: "Who invented lightbulb?", options: ["Tesla", "Edison", "Bell", "Franklin"], correctIndex: 1, explanation: "Edison (commercial).", isBonus: false },
  { id: 'g43', category: Category.GENERAL, text: "Capital of Italy?", options: ["Milan", "Venice", "Rome", "Naples"], correctIndex: 2, explanation: "Rome.", isBonus: false },
  { id: 'g44', category: Category.GENERAL, text: "Sides of a triangle?", options: ["3", "4", "5", "6"], correctIndex: 0, explanation: "3.", isBonus: false },
  { id: 'g45', category: Category.GENERAL, text: "Color of Emerald?", options: ["Red", "Blue", "Green", "Yellow"], correctIndex: 2, explanation: "Green.", isBonus: false },
  { id: 'g46', category: Category.GENERAL, text: "Fastest bird?", options: ["Eagle", "Falcon", "Hawk", "Ostrich"], correctIndex: 1, explanation: "Peregrine Falcon.", isBonus: false },
  { id: 'g47', category: Category.GENERAL, text: "Where are Pyramids?", options: ["Mexico", "Egypt", "Peru", "China"], correctIndex: 1, explanation: "Egypt.", isBonus: false },
  { id: 'g48', category: Category.GENERAL, text: "Author of Harry Potter?", options: ["Tolkien", "Rowling", "Lewis", "Dahl"], correctIndex: 1, explanation: "J.K. Rowling.", isBonus: false },
  { id: 'g49', category: Category.GENERAL, text: "Mickey Mouse has how many fingers?", options: ["3", "4", "5", "6"], correctIndex: 1, explanation: "4.", isBonus: true },
  { id: 'g50', category: Category.GENERAL, text: "Zero in Roman Numerals?", options: ["0", "X", "None", "Z"], correctIndex: 2, explanation: "Romans had no zero.", isBonus: true }
];
